A0-2431: Add rolling update partition input to updatenets (#1191)
* Add rolling update partition input to updatenets

diff --git a/.github/actions/create-featurenet/action.yml b/.github/actions/create-featurenet/action.yml
--- a/.github/actions/create-featurenet/action.yml
+++ b/.github/actions/create-featurenet/action.yml
@@ -47,6 +47,11 @@ inputs:
     description: "Set to 'true' if it is just featurenet update"
     required: false
     default: 'false'
+  rolling-update-partition:
+    # yamllint disable-line rule:line-length
+    description: "All aleph-node-validator-N with an ordinal N that is great than or equal to the partition will be updated. Default value: 0"
+    required: false
+    default: '0'
 
 runs:
   using: "composite"
@@ -80,6 +85,14 @@ runs:
         ]]
         then
           echo "!!! Invalid feature net node image tag"
+          exit 1
+        fi
+        if [[
+          "${{ inputs.update }}" == "true" && \
+          ! "${{ inputs.rolling-update-partition }}" =~ ^[0-9]$
+        ]]
+        then
+          echo "!!! Partition for Rolling Update is invalid"
           exit 1
         fi
 
@@ -129,7 +142,10 @@ runs:
         pr_image="${{ inputs.ecr-public-registry }}feature-env-aleph-node:${pr_image_tag}"
         ./Ops.sh create-featurenet \
           "${{ env.APP_NAME }}" \
-          "${pr_image}"
+          "${pr_image}" \
+          "false" \
+          "false" \
+          "${{ inputs.update == 'true' && inputs.rolling-update-partition || '0' }}"
 
     - name: Start featurenet from testnet/mainnet
       if: inputs.aleph-node-image == 'testnet' || inputs.aleph-node-image == 'mainnet'
@@ -157,7 +173,10 @@ runs:
         pr_image="${{ inputs.ecr-public-registry }}aleph-node:${{ inputs.aleph-node-image }}"
         ./Ops.sh create-featurenet \
           "${{ env.APP_NAME }}" \
-          "${pr_image}"
+          "${pr_image}" \
+          "false" \
+          "false" \
+          "${{ inputs.update == 'true' && inputs.rolling-update-partition || '0' }}"
 
     - name: Commit featurenet change
       uses: EndBug/add-and-commit@v9.1.1
diff --git a/.github/workflows/updatenet-update.yml b/.github/workflows/updatenet-update.yml
--- a/.github/workflows/updatenet-update.yml
+++ b/.github/workflows/updatenet-update.yml
@@ -12,6 +12,10 @@ on:
         description: Node image tag
         required: true
         type: string
+      rolling-update-partition:
+        description: Rolling Update Partition <0, N-1>
+        required: true
+        type: string
 
 jobs:
   check-vars-and-secrets:
@@ -39,6 +43,11 @@ jobs:
           ]]
           then
             echo "!!! Invalid destination node image tag"
+            exit 1
+          fi
+          if [[ ! "${{ inputs.rolling-update-partition }}" =~ ^[0-9]$ ]]
+          then
+            echo "!!! Invalid rolling update partition"
             exit 1
           fi
 
@@ -69,6 +78,7 @@ jobs:
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
           featurenet-name: fe-updnet-${{ inputs.name }}
           update: 'true'
+          rolling-update-partition: '${{ inputs.rolling-update-partition }}'
 
       - name: Wait for the testnet aleph-node binary to accept some blocks
         uses: juliangruber/sleep-action@v2.0.0
