A0-2998: Put 'true' in double quote in one the conditions to check if that helps (#1346)
# Description
Even though input as a boolean, its value in condition is cast to
string.

diff --git a/.github/workflows/_check-vars-and-secrets.yml b/.github/workflows/_check-vars-and-secrets.yml
--- a/.github/workflows/_check-vars-and-secrets.yml
+++ b/.github/workflows/_check-vars-and-secrets.yml
@@ -5,6 +5,11 @@ name: Check vars and secrets
 on:
   workflow_call:
     inputs:
+      check-dev-vars:
+        description: Should dev vars be checked
+        required: false
+        type: boolean
+        default: true
       check-vars:
         description: Should vars be checked
         required: false
@@ -21,14 +26,14 @@ jobs:
     name: Check available vars and secrets
     runs-on: ubuntu-20.04
     steps:
-      - name: Check vars
-        if: inputs.check-vars == true
+      - name: Check dev vars
         run: |
+          if [[ "${{ inputs.check-dev-vars }}" != "true" ]]; then
+            echo "Skipping dev vars check"
+            exit 0
+          fi
+
           if [[ \
-            -z "${{ vars.ECR_PUBLIC_HOST }}" || \
-            -z "${{ vars.ECR_PUBLIC_REGISTRY }}" || \
-            -z "${{ vars.DOCKERHUB_ALEPH_NODE_REPO }}" || \
-            -z "${{ vars.ECR_ALEPH_NODE_REPO }}" || \
             -z "${{ vars.RUST_TOOLCHAIN_NIGHTLY }}" \
           ]]; then
             echo "!!! Some repository variables are either missing or empty."
@@ -36,9 +41,31 @@ jobs:
             exit 1
           fi
 
-      - name: Check secrets
-        if: inputs.check-secrets == true
+      - name: Check vars
         run: |
+          if [[ "${{ inputs.check-vars }}" != "true" ]]; then
+            echo "Skipping vars check"
+            exit 0
+          fi
+
+          if [[ \
+            -z "${{ vars.ECR_PUBLIC_HOST }}" || \
+            -z "${{ vars.ECR_PUBLIC_REGISTRY }}" || \
+            -z "${{ vars.DOCKERHUB_ALEPH_NODE_REPO }}" || \
+            -z "${{ vars.ECR_ALEPH_NODE_REPO }}" \
+          ]]; then
+            echo "!!! Some repository variables are either missing or empty."
+            echo "!!! Please check either repository or organization settings."
+            exit 1
+          fi
+
+      - name: Check secrets
+        run: |
+          if [[ "${{ inputs.check-secrets }}" != "true" ]]; then
+            echo "Skipping secrets check"
+            exit 0
+          fi
+
           if [[ \
             -z "${{ secrets.ARGOCD_DEVNET_HOST }}" || \
             -z "${{ secrets.ARGO_SYNC_USER_TOKEN }}" || \
