A0-3203: Add 'internal' input to updatenets (#1391)
# Description

* Adds a boolean input called `internal` to updatenets that will make
the workflow create a net accessible only via VPN.
* Also, a small refactor of how net name is passed from workflows to
actions.

## Type of change

- New feature (non-breaking change which adds functionality)

---------

Co-authored-by: Marcin <marcin.radecki@cardinals.cc>

diff --git a/.github/workflows/create-featurenet.yml b/.github/workflows/create-featurenet.yml
--- a/.github/workflows/create-featurenet.yml
+++ b/.github/workflows/create-featurenet.yml
@@ -4,8 +4,12 @@ name: Create featurenet
 on:
   workflow_call:
     inputs:
-      append-run-id-to-name:
-        description: When set to 'true' then run ID will be appended to featurenet name
+      featurenet-name:
+        description: 'Name of featurenet'
+        type: string
+        required: true
+      internal:
+        description: 'Internal network, accessible from VPN only'
         required: false
         type: boolean
         default: false
@@ -22,10 +26,48 @@ on:
           - 3h
           - 96h
           - never
+      featurenet-name:
+        description: 'Name of featurenet'
+        type: string
+        required: true
 
 jobs:
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,48}$
+          ]]
+          then
+            echo "!!! Invalid featurenet name"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
+  get-final-names:
+    name: Get final names
+    runs-on: ubuntu-20.04
+    needs: [validate-inputs]
+    outputs:
+      final-featurenet-name: ${{ steps.get-final-names.outputs.final-featurenet-name }}
+    steps:
+      - name: Get final names
+        id: get-final-names
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          final_featurenet_name_local=${{ inputs.featurenet-name }}
+          echo "final-featurenet-name=$final_featurenet_name_local" >> $GITHUB_OUTPUT
+        # yamllint enable rule:line-length
+
   check-vars-and-secrets:
     name: Check vars and secrets
+    needs: [get-final-names]
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
 
@@ -58,7 +100,7 @@ jobs:
     secrets: inherit
 
   create-featurenet:
-    needs: [push-featurnet-node-image-to-ecr]
+    needs: [push-featurnet-node-image-to-ecr, get-final-names]
     name: Create featurenet based on the PR
     runs-on: [self-hosted, Linux, X64, small]
     outputs:
@@ -79,10 +121,9 @@ jobs:
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-
-      - name: Call action get-ref-properties
-        id: get-ref-properties
-        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v1
+          featurenet-name: ${{ needs.get-final-names.outputs.final-featurenet-name }}
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
       - name: Start featurenet Deployment
         uses: bobheadxi/deployments@v1.1.0
@@ -90,12 +131,13 @@ jobs:
         with:
           step: start
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: ${{ steps.get-ref-properties.outputs.branch-name-flattened }}
+          env: ${{ needs.get-final-names.outputs.final-featurenet-name }}
           ref: ${{ github.head_ref }}
           override: true
 
       - name: Create featurenet from scratch
         uses: ./.github/actions/create-featurenet
+        id: create-featurenet
         with:
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
@@ -104,7 +146,10 @@ jobs:
           ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
           expiration: ${{ inputs.expiration == '' && '48h' || inputs.expiration }}
-          append-run-id-to-name: "${{ inputs.append-run-id-to-name }}"
+          featurenet-name: ${{ needs.get-final-names.outputs.final-featurenet-name }}
+          internal: "${{ inputs.internal }}"
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
       - name: Wait for the aleph-node binary to accept some blocks
         uses: ./.github/actions/wait-for-finalized-heads
@@ -112,7 +157,7 @@ jobs:
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           # yamllint disable-line rule:line-length
-          json-rpc-endpoint: https://ws-fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo }}${{ inputs.append-run-id-to-name == 'true' && format('-{0}', github.run_id) || '' }}.dev.azero.dev
+          json-rpc-endpoint: https://${{ steps.create-featurenet.outputs.ws-hostname }}
 
       - name: Remove deleted label if present
         uses: actions-ecosystem/action-remove-labels@v1.3.0
@@ -128,10 +173,10 @@ jobs:
           step: finish
           token: ${{ secrets.CI_GH_TOKEN }}
           status: ${{ job.status }}
-          env: ${{ steps.get-ref-properties.outputs.branch-name-flattened }}
+          env: ${{ needs.get-final-names.outputs.final-featurenet-name }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
           # yamllint disable-line rule:line-length
-          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2Fws-fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo }}${{ inputs.append-run-id-to-name == 'true' && format('-{0}', github.run_id) || '' }}.dev.azero.dev#/explorer
+          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-featurenet.outputs.ws-hostname }}#/explorer
           ref: ${{ github.head_ref }}
 
       - name: Remove deployment request label if exists
@@ -142,6 +187,7 @@ jobs:
           github_token: ${{ secrets.CI_GH_TOKEN }}
 
       - name: Add label to mark that featurenet has been created
+        if: github.event_name == 'pull_request'
         uses: actions-ecosystem/action-add-labels@v1.1.0
         with:
           labels: 'state:created-featurenet'
diff --git a/.github/workflows/delete-featurenet.yml b/.github/workflows/delete-featurenet.yml
--- a/.github/workflows/delete-featurenet.yml
+++ b/.github/workflows/delete-featurenet.yml
@@ -4,30 +4,64 @@ name: Delete featurenet
 on:
   workflow_call:
     inputs:
-      append-run-id-to-name:
-        description: When set to 'true' then run ID will be appended to featurenet name
-        required: false
-        type: boolean
-        default: false
+      featurenet-name:
+        description: 'Name of featurenet'
+        type: string
+        required: true
+  workflow_dispatch:
+    inputs:
+      featurenet-name:
+        description: 'Name of featurenet'
+        type: string
+        required: true
 
 jobs:
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,48}$
+          ]]
+          then
+            echo "!!! Invalid featurenet name"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
+  get-final-names:
+    needs: [validate-inputs]
+    name: Get final names
+    runs-on: ubuntu-20.04
+    outputs:
+      final-featurenet-name: ${{ steps.get-final-names.outputs.final-featurenet-name }}
+    steps:
+      - name: Get final names
+        id: get-final-names
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          final_featurenet_name_local=${{ inputs.featurenet-name }}
+          echo "final-featurenet-name=$final_featurenet_name_local" >> $GITHUB_OUTPUT
+        # yamllint enable rule:line-length
+
   check-vars-and-secrets:
+    needs: [get-final-names]
     name: Check vars and secrets
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
 
   delete-featurenet:
-    needs: [check-vars-and-secrets]
+    needs: [check-vars-and-secrets, get-final-names]
     name: Delete featurenet
     runs-on: [self-hosted, Linux, X64, small]
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
-
-      - name: Call action get-ref-properties
-        id: get-ref-properties
-        # yamllint disable-line rule:line-length
-        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v1
 
       - name: Delete featurenet app and data
         uses: ./.github/actions/delete-featurenet
@@ -40,7 +74,9 @@ jobs:
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          append-run-id-to-name: "${{ inputs.append-run-id-to-name }}"
+          featurenet-name: ${{ needs.get-final-names.outputs.final-featurenet-name }}
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
       - name: Remove created label if present
         uses: actions-ecosystem/action-remove-labels@v1.3.0
@@ -54,7 +90,7 @@ jobs:
         with:
           step: deactivate-env
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: ${{ steps.get-ref-properties.outputs.branch-name-flattened }}
+          env: ${{ needs.get-final-names.outputs.final-featurenet-name }}
           desc: Environment was deleted
           debug: true
 
@@ -62,7 +98,7 @@ jobs:
         uses: strumwolf/delete-deployment-environment@v2
         with:
           token: ${{ secrets.CI_GH_TOKEN }}
-          environment: ${{ steps.get-ref-properties.outputs.branch-name-flattened }}
+          environment: ${{ needs.get-final-names.outputs.final-featurenet-name }}
 
       - name: Remove delete deployment request label if exists
         if: contains(github.event.pull_request.labels.*.name, 'trigger:delete-featurenet')
@@ -72,6 +108,7 @@ jobs:
           github_token: ${{ secrets.CI_GH_TOKEN }}
 
       - name: Add label to mark that featurenet has been deleted
+        if: github.event_name == 'pull_request'
         uses: actions-ecosystem/action-add-labels@v1.1.0
         with:
           labels: 'state:deleted-featurenet'
diff --git a/.github/workflows/updatenet-update.yml b/.github/workflows/updatenet-update.yml
--- a/.github/workflows/updatenet-update.yml
+++ b/.github/workflows/updatenet-update.yml
@@ -23,6 +23,11 @@ on:
         description: 'Number of replicas to start, from 0 to 50'
         required: true
         default: '5'
+      internal:
+        description: 'Internal network, accessible from VPN only'
+        required: false
+        type: boolean
+        default: false
 
 jobs:
   check-vars-and-secrets:
@@ -40,7 +45,7 @@ jobs:
       - name: Validate inputs
         shell: bash
         run: |
-          if [[ ! "${{ inputs.name }}" =~ ^[a-z0-9][a-z0-9\-]{4,30}$ ]]; then
+          if [[ ! "${{ inputs.name }}" =~ ^[a-z0-9][a-z0-9\-]{4,44}$ ]]; then
             echo "!!! Invalid updatenet name"
             exit 1
           fi
@@ -59,6 +64,23 @@ jobs:
             exit 1
           fi
 
+      - name: Get updatenet name
+        id: get-updatenet-name
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+            "${{ inputs.name }}" != "" && \
+            ! "${{ inputs.name }}" =~ ^[a-z0-9][a-z0-9\-]{4,30}$
+          ]]
+          then
+            echo "!!! Invalid name"
+            exit 1
+          fi
+          final_updatenet_name_local=updnet-${{ inputs.name }}
+          echo "final-updatenet-name=$final_updatenet_name_local" >> $GITHUB_OUTPUT
+        # yamllint enable rule:line-length
+
       - name: Checkout repo
         uses: actions/checkout@v4
 
@@ -68,11 +90,12 @@ jobs:
         with:
           step: start
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: updatenet-${{ inputs.name }}
+          env: ${{ steps.get-updatenet-name.outputs.final-updatenet-name }}
           override: true
 
       - name: Update featurenet data, app and deploy it
         uses: ./.github/actions/create-featurenet
+        id: create-updatenet
         with:
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
@@ -80,17 +103,21 @@ jobs:
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          featurenet-name: fe-updnet-${{ inputs.name }}
+          featurenet-name: ${{ steps.get-updatenet-name.outputs.final-updatenet-name }}
           featurenet-aleph-node-image: ${{ inputs.destination }}
           rolling-update-partition: ${{ inputs.rolling-update-partition }}
           replicas: ${{ inputs.replicas }}
+          internal: ${{ inputs.internal && 'true' || 'false' }}
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
+          hard-refresh: 'true'
 
       - name: Wait for the aleph-node binary to accept some blocks
         uses: ./.github/actions/wait-for-finalized-heads
         with:
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
-          json-rpc-endpoint: https://ws-fe-updnet-${{ inputs.name }}.dev.azero.dev
+          json-rpc-endpoint: https://${{ steps.create-updatenet.outputs.ws-hostname }}
 
       - name: Finish featurenet Deployment
         uses: bobheadxi/deployments@v1
@@ -99,7 +126,7 @@ jobs:
           step: finish
           token: ${{ secrets.CI_GH_TOKEN }}
           status: ${{ job.status }}
-          env: updatenet-${{ inputs.name }}
+          env: ${{ steps.get-updatenet-name.outputs.final-updatenet-name }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
           # yamllint disable-line rule:line-length
-          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2Fws-fe-updnet-${{ inputs.name }}.dev.azero.dev#/explorer
+          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-updatenet.outputs.ws-hostname }}#/explorer
