Testnet pipeline changed to match proper branch (#238)
Co-authored-by: Szymon Królikowski <s.krolikowski@tenesys.pl>

diff --git a/.github/workflows/deploy-testnet.yml b/.github/workflows/deploy-testnet.yml
--- a/.github/workflows/deploy-testnet.yml
+++ b/.github/workflows/deploy-testnet.yml
@@ -48,13 +48,21 @@ jobs:
           DEVNET_IMAGE: public.ecr.aws/p6e8q1z1/aleph-node:${{ steps.vars.outputs.sha_short }}
           TESTNET_IMAGE: public.ecr.aws/p6e8q1z1/aleph-node:${{ steps.vars.outputs.branch }}
         run: |
-          docker pull ${{ env.DEVNET_IMAGE }}
-          docker tag ${{ env.DEVNET_IMAGE }} ${{ env.TESTNET_IMAGE }}
-          docker push ${{ env.TESTNET_IMAGE }}
+          export image_not_exist=$(docker manifest inspect ${{ env.DEVNET_IMAGE }} &> /dev/null ; echo $?)
+
+          if [ $image_not_exist -eq 1 ]; then
+            echo "::error title=Wrong docker image tag::Docker image ${{ env.DEVNET_IMAGE }} doesn't exist"
+            exit 1
+          else
+            docker pull ${{ env.DEVNET_IMAGE }}
+            docker tag ${{ env.DEVNET_IMAGE }} ${{ env.TESTNET_IMAGE }}
+            docker push ${{ env.TESTNET_IMAGE }}
+          fi
           
       - name: GIT | Checkout aleph-apps repo
         uses: actions/checkout@master
         with:
+          ref: testnet
           repository: Cardinal-Cryptography/aleph-apps
           token: ${{ secrets.CI_GH_TOKEN }}
           path: "aleph-apps"
@@ -89,7 +97,7 @@ jobs:
           message: "Updating Testnet docker image tag for pre-release: ${{ steps.vars.outputs.branch }}"
           add: "*.yaml"
           cwd: "aleph-apps"
-          branch: main
+          branch: testnet
         env:
           GITHUB_TOKEN: ${{ secrets.CI_GH_TOKEN }}
 
