A0-3467: Unify featurenet creation (#1520)
# Description

This PR introduced completely new refactored featurenets which has the
following important changes:
* merged two separate `create-from-branch` and `create-from-net`
workflows into one
* simplified inputs where you can enter either 'mainnet', 'testnet' or
any git reference (such as tag, commit hash or branch)
* simplified logic - the image is always built, no more nasty 'if'
conditions everywhere
* reduced code, and more of the steps pushed further to actions in
`github-actions` (and these guys got refactored and simplified as well)

## Type of change

- Breaking change to featurenets, however, nothing worrying as of this
moment there are no important featurenets running

# Checklist:

- I have added tests
- I have marked the documentation as out-of-date - we'll deal with it
ASAP after the merge

---------

Co-authored-by: Marcin <marcin.radecki@cardinals.cc>

diff --git a/.github/workflows/featurenet-create.yml b/.github/workflows/featurenet-create.yml
--- a/.github/workflows/featurenet-create.yml
+++ b/.github/workflows/featurenet-create.yml
@@ -1,11 +1,15 @@
 ---
-name: FE - Create from branch
+name: FE - Create
 
 on:
   workflow_dispatch:
     inputs:
       featurenet-name:
         description: 'Name of featurenet'
+        type: string
+        required: true
+      ref:
+        description: "git ref: hash, branch, tag - or 'mainnet' or 'testnet'"
         type: string
         required: true
       expiration:
@@ -36,6 +40,10 @@ on:
         description: 'Name of featurenet'
         type: string
         required: true
+      ref:
+        description: "git ref: hash, branch, tag - or 'mainnet' or 'testnet'"
+        type: string
+        required: true
       expiration:
         description: 'Time after which featurenet will be removed'
         required: false
@@ -61,11 +69,12 @@ jobs:
         shell: bash
         # yamllint disable rule:line-length
         run: |
-          if [[
-          ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$
-          ]]
-          then
+          if [[ ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$ ]]; then
             echo '!!! Invalid featurenet name'
+            exit 1
+          fi
+          if [[ ! '${{ inputs.ref }}' =~ ^[a-zA-Z0-9][a-zA-Z0-9\._\-]{1,48}$ ]]; then
+            echo "!!! Invalid ref"
             exit 1
           fi
         # yamllint enable rule:line-length
@@ -77,41 +86,51 @@ jobs:
     secrets: inherit
 
   build-test-node-and-runtime:
+    if: ${{ inputs.ref != 'mainnet' && inputs.ref != 'testnet' }}
     name: Build test node and runtime
     needs: [check-vars-and-secrets]
     uses: ./.github/workflows/_build-test-node-and-runtime.yml
+    with:
+      ref: ${{ inputs.ref }}
     secrets: inherit
 
-  store-test-node-and-runtime:
-    name: Store test node and runtime in Devnet bucket
-    runs-on: ubuntu-20.04
+  push-featurenet-test-node-image-to-ecr:
+    if: ${{ inputs.ref != 'mainnet' && inputs.ref != 'testnet' }}
     needs: [build-test-node-and-runtime]
-    steps:
-      - name: Checkout aleph-node source code
-        uses: actions/checkout@v4
-
-      - name: Store test node and runtime
-        uses: ./.github/actions/store-node-and-runtime
-        with:
-          profile: test
-          aws-access-key-id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
-          aws-bucket: ${{ secrets.CI_DEVNET_S3BUCKET_NAME }}
-
-  push-featurnet-node-image-to-ecr:
-    needs: [store-test-node-and-runtime]
-    name: Build and push PR tesdocker image to ECR
-    uses: ./.github/workflows/_build-and-push-pull-request-image-to-featurenets.yml
+    name: Build and push PR test docker image to ECR
+    uses: ./.github/workflows/_build-and-push-test-image-to-featurenets.yml
+    with:
+      ref: ${{ inputs.ref }}
     secrets: inherit
 
-  create-featurenet:
-    needs: [push-featurnet-node-image-to-ecr]
-    name: Create featurenet based on the PR
+  create-featurenet-from-branch:
+    if: ${{ inputs.ref != 'mainnet' && inputs.ref != 'testnet' }}
+    needs: [push-featurenet-test-node-image-to-ecr]
+    name: Create featurenet from branch
     # yamllint disable-line rule:line-length
-    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create-from-branch.yml@v4
+    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v5
     secrets: inherit
     with:
       expiration: ${{ inputs.expiration }}
       replicas: ${{ inputs.replicas }}
       internal: ${{ inputs.internal && true || false }}
       featurenet-name: ${{ inputs.featurenet-name }}
+      aleph-node-image: ${{ needs.push-featurenet-test-node-image-to-ecr.outputs.image-tag }}
+      featurenet-ecr-repo: true
+      delete-first: true
+
+  create-featurenet-from-net:
+    if: ${{ inputs.ref == 'mainnet' || inputs.ref == 'testnet' }}
+    needs: [check-vars-and-secrets]
+    name: Create featurenet from net
+    # yamllint disable-line rule:line-length
+    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v5
+    secrets: inherit
+    with:
+      expiration: ${{ inputs.expiration }}
+      replicas: ${{ inputs.replicas }}
+      internal: ${{ inputs.internal && true || false }}
+      featurenet-name: ${{ inputs.featurenet-name }}
+      aleph-node-image: ${{ inputs.ref }}
+      featurenet-ecr-repo: false
+      delete-first: true
diff --git a/.github/workflows/featurenet-update.yml b/.github/workflows/featurenet-update.yml
--- a/.github/workflows/featurenet-update.yml
+++ b/.github/workflows/featurenet-update.yml
@@ -8,8 +8,8 @@ on:
         description: Name of featurenet
         required: true
         type: string
-      destination:
-        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
+      ref:
+        description: 'git ref: hash, branch, tag'
         required: true
         type: string
       rolling-update-partition:
@@ -28,52 +28,72 @@ on:
       internal:
         description: 'Internal network, accessible from VPN only'
         required: true
-        type: boolean
-        default: false
-  workflow_call:
-    inputs:
-      featurenet-name:
-        description: Name of featurenet
-        required: true
-        type: string
-      destination:
-        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
-        required: true
-        type: string
-      rolling-update-partition:
-        description: |
-          Number from 0 to N-1, where N is size of am existing featurenet.
-          All aleph-node-validator-N with an ordinal N that is great than or equal to the partition
-          will be updated. If not specified, all nodes will be updated.
-        required: false
-        default: "0"
-        type: string
-      replicas:
-        description: 'Number of replicas to start, from 0 to 50'
-        required: false
-        default: '5'
-        type: string
-      internal:
-        description: 'Internal network, accessible from VPN only'
-        required: false
         type: boolean
         default: false
 
 jobs:
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[ ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$ ]]; then
+            echo '!!! Invalid featurenet name'
+            exit 1
+          fi
+          if [[ ! '${{ inputs.ref }}' =~ ^[a-zA-Z0-9][a-zA-Z0-9\._\-]{1,48}$ ]]; then
+            echo "!!! Invalid ref"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
+  check-image-existence:
+    needs: [validate-inputs]
+    name: Check if node image tag exists
+    runs-on: ubuntu-20.04
+    outputs:
+      image-tag: ${{ steps.check-image-exists.outputs.image-tag }}
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.ref }}
+
+      - name: Call action get-ref-properties
+        id: get-ref-properties
+        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v4
+
+      - name: Check if node image tag exists
+        id: check-image-exists
+        shell: bash
+        run: |
+          image_tag='${{ steps.get-ref-properties.outputs.sha }}'
+          image='${{ vars.ECR_PUBLIC_REGISTRY }}'aleph-node:${image_tag}
+          if ! docker manifest inspect ${image}; then
+           echo "!! Image ${image} does not exist.";
+           exit 1;
+          fi
+          echo "image-tag=${image_tag}" >> $GITHUB_OUTPUT
+
   check-vars-and-secrets:
+    needs: [check-image-existence]
     name: Check vars and secrets
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
 
   update-featurenet:
-    needs: [check-vars-and-secrets]
+    needs: [check-vars-and-secrets, check-image-existence]
     name: Update featurenet
     # yamllint disable-line rule:line-length
-    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-update.yml@v4
+    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v5
     secrets: inherit
     with:
       featurenet-name: ${{ inputs.featurenet-name }}
-      destination: ${{ inputs.destination }}
+      aleph-node-image: ${{ needs.check-image-existence.outputs.image-tag }}
       rolling-update-partition: ${{ inputs.rolling-update-partition }}
       replicas: ${{ inputs.replicas }}
       internal: ${{ inputs.internal && true || false }}
+      delete-first: false
