A0-2120: Make yaml-validate workflow fail on errors (#1036)
* Make yaml-validate workflow fail on errors

* Tweak the bash script in yaml-validate to not crash

---------

Co-authored-by: Marcin <marcin.radecki@cardinals.cc>

diff --git a/.github/workflows/yaml-validate.yml b/.github/workflows/yaml-validate.yml
--- a/.github/workflows/yaml-validate.yml
+++ b/.github/workflows/yaml-validate.yml
@@ -23,7 +23,23 @@ jobs:
         env:
           DOCKER_IMAGE: public.ecr.aws/p6e8q1z1/github-workflows-validator:0.3.1
         run: |
+          set +e
           docker pull ${DOCKER_IMAGE}
           docker run --rm --name tmp-ghv -v $(pwd)/.github:/dot-github \
             ${DOCKER_IMAGE} \
-            validate -p /dot-github
+            validate -p /dot-github > validation_result
+          echo "------------------------------------------------"
+          cat validation_result
+          echo "------------------------------------------------"
+          cat validation_result | grep '^E' > validation_result_errors
+          if [[ $(cat validation_result_errors | wc -l) > 0 ]]; then
+            echo "!!!"
+            echo "!!! Errors have been found in GitHub YAML files!"
+            echo "!!!"
+            echo "------------------------------------------------"
+            cat validation_result_errors
+            echo "------------------------------------------------"
+            echo "!!! Please fix them!"
+            echo "!!!"
+            exit 1
+          fi
